export const productsArray = [
    {
        id: 1,
        name: 'iPhone 13 Pro',
        description: 'This is iPhone 13 Pro',
        capacity: 264,
        type: 'phone',
        price: 1100,
        image: '/images/iphone-black.jpg',
    },
    {
        id: 2,
        name: 'iPhone 12 Pro',
        description: 'This is iPhone 12 Pro',
        capacity: 64,
        type: 'phone',
        price: 800,
        image: '/images/iphone-blue.jpg',
    },
    {
        id: 3,
        name: 'iPhone X',
        description: 'This is iPhone X',
        capacity: 64,
        type: 'phone',
        price: 500,
        image: '/images/iphone-gold.jpg',
    },
    {
        id: 4,
        name: 'iPhone 13 Pro Max',
        description: 'This is 13 Pro Max',
        capacity: 512,
        type: 'phone',
        price: 2500,
        image: '/images/iphone-gray.jpg',
    },
    {
        id: 5,
        name: 'iPhone X',
        description: 'This is iPhone X',
        capacity: 64,
        type: 'phone',
        price: 500,
        image: '/images/iphone-purple.jpg',
    },
    {
        id: 6,
        name: 'iPhone 12 Pro',
        description: 'This is iPhone 12 Pro',
        capacity: 64,
        type: 'phone',
        price: 800,
        image: '/images/iphone-red.jpg',
    },
]
