export const productsArray = [
    {
        id: 1,
        name: 'iPhone 13 Pro',
        description: 'This is iPhone 13 Pro',
        capacity: '264',
        type: 'phone',
        price: '1100',
    },
    {
        id: 2,
        name: 'iPhone 12 Pro',
        description: 'This is iPhone 12 Pro',
        capacity: '64',
        type: 'phone',
        price: '800',
    },
    {
        id: 3,
        name: 'iPhone X',
        description: 'This is iPhone X',
        capacity: '64',
        type: 'phone',
        price: '500',
    },
    {
        id: 4,
        name: 'iPhone 13 Pro Max',
        description: 'This is 13 Pro Max',
        capacity: '512',
        type: 'phone',
        price: '2500',
    },
    {
        id: 5,
        name: 'iPhone X',
        description: 'This is iPhone X',
        capacity: '64',
        type: 'phone',
        price: '500',
    },
    {
        id: 6,
        name: 'iPhone 12 Pro',
        description: 'This is iPhone 12 Pro',
        capacity: '64',
        type: 'phone',
        price: '800',
    },
]
